### ISSUE TITLE
"Unicode char \u8: not set up for use with LaTeX"

### ISSUE THREAD

**Issue by RoboCafaz** [lawrancej/CompilerDesign#39]
A unicode character somewhere in the textbook is preventing pandoc from generating. Unfortunately, pandoc is not very verbose and does not give any more detail.

**Comment by lawrancej** [comment]
It was the UTF-8 BOM. The `generate.sh` script now removes this from files automatically.

**Comment by lawrancej** [comment]
The issue was smart quotes. Added smart quote removal into generate.sh
